export const themeConfig = {
    light: {
        bg: 'bg-light-bg',
        text: 'text-light-text',
        border: 'border-light-accent',
        accentBg: 'bg-light-accent',
        accentText: 'text-light-bg',
        hoverBg: 'hover:bg-gray-700',
        hoverText: 'hover:text-white',
    },
    dark: {
        bg: 'bg-dark-bg',
        text: 'text-dark-text',
        border: 'border-dark-accent',
        accentBg: 'bg-dark-accent',
        accentText: 'text-dark-bg',
        hoverBg: 'hover:bg-purple-700',
        hoverText: 'hover:text-white',
    },
    ocean: {
        bg: 'bg-ocean-bg',
        text: 'text-ocean-text',
        border: 'border-ocean-accent',
        accentBg: 'bg-ocean-accent',
        accentText: 'text-ocean-bg',
        hoverBg: 'hover:bg-blue-600',
        hoverText: 'hover:text-white',
    },
    forest: {
        bg: 'bg-forest-bg',
        text: 'text-forest-text',
        border: 'border-forest-accent',
        accentBg: 'bg-forest-accent',
        accentText: 'text-forest-bg',
        hoverBg: 'hover:bg-green-700',
        hoverText: 'hover:text-white',
    },
    sunset: {
        bg: 'bg-sunset-bg',
        text: 'text-sunset-text',
        border: 'border-sunset-accent',
        accentBg: 'bg-sunset-accent',
        accentText: 'text-sunset-bg',
        hoverBg: 'hover:bg-orange-600',
        hoverText: 'hover:text-white',
    },
};